---
- name: Configurar servidor web
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Iniciar y habilitar NGINX
      systemd:
        name: nginx
        state: started
        enabled: yes
